#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#
 sudo apt-get update
 sudo apt-get install nginx
 sudo ufw 'Nginx HTTP'

 echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing if configuration files are ok
 sudo nginx -t

# Reloading server to display updated content
 sudo service nginx reload
