#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 115061-web-01 100.26.219.126 check port 80
        server 115061-web-02 204.236.240.229 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
