#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# only display:
# username, user id and home directory path for the user
while read i; do
    echo "$i" | cut -d':' -f 1,3,6
done < /etc/passwd
